import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
          <title>React Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className='bg-blue-700 h-screen'>
          <h1>Hello</h1>
        </section>
      </main>
    </div>
  );
}